'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { BookOpen, MessageCircle, Sparkles, Lightbulb, Send, Check, X, GraduationCap, RotateCcw, ClipboardList, ShieldCheck, ChevronRight } from 'lucide-react';
import { useModal } from '@/lib/use-modal';
import { defaultCourse, topics, type Message, type TutorReply } from '@/lib/course';
type Entry={student?:string;reply?:TutorReply};
export default function Home(){
 const [course,setCourse]=useState(defaultCourse),[topicId,setTopicId]=useState(topics[0].id),[entries,setEntries]=useState<Entry[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[aiReady,setAiReady]=useState(false),[loaded,setLoaded]=useState(false),[modal,setModal]=useState(false),[sent,setSent]=useState(''),[sending,setSending]=useState(false),[include,setInclude]=useState(false),[question,setQuestion]=useState('');
 const [identity,setIdentity]=useState({name:'',studentId:'',email:''}),[consent,setConsent]=useState(false);const requestId=useRef('');const bottom=useRef<HTMLDivElement>(null);const topic=topics.find(t=>t.id===topicId)!; useModal(modal,()=>{if(!sending)setModal(false)});
 useEffect(()=>{fetch('/api/config').then(async r=>{const d=await r.json() as {error?:string;course:typeof defaultCourse;aiReady:boolean};if(!r.ok)throw Error(d.error);setCourse(d.course);setAiReady(d.aiReady);setLoaded(true)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(entries.length)bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[entries,busy]);
 const history:Message[]=entries.flatMap<Message>(e=>e.student?[{role:'user' as const,content:e.student}]:e.reply?[{role:'assistant' as const,content:JSON.stringify(e.reply)}]:[]);
 function reset(id=topicId){if(entries.length&&!window.confirm('현재 대화를 끝내고 새로 시작할까요? 교수자에게 제출한 질문은 유지됩니다.'))return;setTopicId(id);setEntries([]);setInput('');setError('')}
 async function chat(action:'discuss'|'hint'|'summary') {if(busy)return; const content=action==='discuss'?input.trim():action==='hint'?'조금 어렵습니다. 짧은 힌트를 주세요.':'지금까지 제 답변을 바탕으로 학습 내용을 정리해주세요.';if(!content)return;setBusy(true);setError('');try{const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:topicId,action,messages:[...history,{role:'user',content}]})});const d=await r.json() as TutorReply & {error?:string};if(!r.ok)throw Error(d.error);setEntries([...entries,{student:content},{reply:d}]);if(action==='discuss')setInput('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function openQuestion(){setQuestion(input.trim()||[...entries].reverse().find(e=>e.student)?.student||'');setSent('');setError('');requestId.current=crypto.randomUUID();setModal(true)}
 async function submit(e:FormEvent){e.preventDefault();setSending(true);setError('');try{const r=await fetch('/api/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...identity,question,topic:topicId,consent,transcript:include?history:[],id:requestId.current})});const d=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(d.error);setSent(d.id);setQuestion('')}catch(e){setError((e as Error).message)}finally{setSending(false)}}
 return <div className="app"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><MessageCircle size={23}/></span>afterclass<span className="brand-dot">.</span></a><span className="top-caption">수업이 끝나도, 질문은 계속됩니다</span><a href="/admin" className="admin-link"><GraduationCap size={18}/>교수자 모드</a></header>
 <div className="workspace"><aside className="sidebar"><div className="course-label">MY CLASSROOM</div><h1>{course.title}</h1><div className="course-meta">{course.week} <span>·</span> 개념 이해와 비판적 사고</div><div className="sidebar-divider"/><p className="section-label">오늘의 학습 주제</p><nav aria-label="학습 주제">{topics.map((t,i)=><button key={t.id} className={`topic ${t.id===topicId?'active':''}`} onClick={()=>reset(t.id)} disabled={busy}><span className="topic-number">0{i+1}</span><span><strong>{t.title}</strong><small>강의자료 {t.pages}</small></span>{t.id===topicId&&<ChevronRight size={16}/>}</button>)}</nav><div className="goal"><BookOpen size={19}/><p className="section-label">이번 대화의 목표</p><p>{topic.goal}</p></div><div className="sidebar-bottom"><ShieldCheck size={17}/><span>생각을 연습하는 공간입니다.<br/>정답을 몰라도 괜찮아요.</span></div></aside>
 <main className="main"><div className="breadcrumb">{course.week} <span>/</span> AI SOCRATIC TUTOR</div><div className="main-heading"><div><h2>질문으로 시작하는 이해</h2><p>배운 내용을 자신의 말로 풀어보세요.</p></div><button className="icon-button" onClick={()=>reset()} aria-label="대화 새로 시작" title="대화 새로 시작" disabled={busy}><RotateCcw size={19}/></button></div><div className="mode-tabs"><span className="tab-active"><Sparkles size={17}/>소크라테스 튜터</span><button onClick={openQuestion}><MessageCircle size={17}/>교수자에게 질문</button><span className="mode-tag">{loaded?(aiReady?'AI 연결됨':'준비 질문 체험'):'수업 불러오는 중'}</span></div>
 <section className="conversation" aria-label="튜터 대화" aria-live="polite"><div className="tutor-intro"><div className="avatar"><Sparkles size={22}/></div><div className="message-body"><div className="speaker">학습 튜터 <span>함께 생각해요</span></div><div className="intro-card"><span className="mini-label">첫 번째 질문</span><h3>{topic.start}</h3><p>완벽한 설명이 아니어도 좋아요. 지금 떠오르는 생각부터 적어보세요.</p></div><div className="source"><BookOpen size={13}/>{course.title} {course.week} · 강의자료 {topic.pages}</div></div></div>
 {entries.map((e,i)=>e.student?<div key={i} className="student-message"><span>나의 생각</span><p>{e.student}</p></div>:<div className="tutor-message" key={i}><div className="avatar small"><Sparkles size={18}/></div><div className="reply"><div className="speaker">{e.reply!.mode==='ai'?'AI 튜터':'준비 질문 안내'}</div><div className="understanding"><b>현재 이해</b><p>{e.reply!.understanding}</p></div><div className="next-question"><b>다음 질문</b><p>{e.reply!.question}</p></div>{e.reply!.hint&&<div className="hint"><b>짧은 힌트</b><p>{e.reply!.hint}</p></div>}{e.reply!.summary&&<div className="summary"><b>학습 정리</b><p>{e.reply!.summary}</p></div>}<small className="source">{e.reply!.source}</small></div></div>)}
 {busy&&<div className="thinking"><Sparkles size={16}/>다음 질문을 생각하고 있어요…</div>}<div ref={bottom}/></section>
 <div className="composer-area">{error&&!modal&&<p role="alert" className="error">{error}</p>}<div className="quick-actions"><button onClick={()=>chat('hint')} disabled={busy||!entries.length||history.length>=16}><Lightbulb size={16}/>힌트 받기</button><button onClick={()=>chat('summary')} disabled={busy||!entries.length||history.length>=16}><ClipboardList size={16}/>학습 정리</button></div><form className="composer" onSubmit={e=>{e.preventDefault();chat('discuss')}}><label className="sr-only" htmlFor="thought">나의 생각 또는 질문</label><textarea id="thought" value={input} maxLength={3000} rows={3} onChange={e=>setInput(e.target.value)} placeholder="내가 이해한 내용이나 궁금한 점을 적어보세요…" disabled={busy||history.length>=16}/><div className="composer-footer"><span>{history.length>=16?'대화를 정리하거나 새 주제로 시작해보세요.':'한 번에 하나씩, 생각을 넓혀갑니다.'}</span><button className="primary" type="submit" disabled={busy||!input.trim()||history.length>=16}><Sparkles size={16}/>{aiReady?'AI와 생각 나누기':'준비 질문으로 이어가기'}</button></div></form><p className="disclaimer">{aiReady?'AI는 틀릴 수 있습니다. 강의자료와 함께 확인하세요. 대화 내용은 AI 서비스로 전송됩니다.':'현재는 강의 기반 준비 질문 모드입니다. AI 연결 후 답변에 맞춘 대화와 학습 정리를 제공합니다.'}<br/>대화는 이 화면에서만 유지되며, 교수자에게 제출할 때 선택한 내용만 저장됩니다.</p></div>
 </main><aside className="right-panel"><div className="note-card"><span className="mini-label">HOW WE LEARN</span><h3>답보다 먼저,<br/>나의 생각.</h3><ol><li><span>1</span><div><b>설명해보기</b><p>지금 이해한 것을 꺼내세요.</p></div></li><li><span>2</span><div><b>다시 생각하기</b><p>질문에 답하며 근거를 살펴요.</p></div></li><li><span>3</span><div><b>내 것으로 만들기</b><p>자신의 말로 다시 설명해요.</p></div></li></ol></div><div className="professor-card"><MessageCircle size={23}/><h3>아직 궁금한가요?</h3><p>혼자 풀리지 않는 질문은 교수자에게 남겨주세요. 답변을 이메일로 받을 수 있어요.</p><button className="secondary" onClick={openQuestion}>교수자에게 질문 남기기</button></div><p className="reference-caption">수업 자료 기반<br/>5주차 감성컴퓨팅 강의자료</p></aside></div>
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!sending)setModal(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="question-heading"><button className="close icon-button" onClick={()=>setModal(false)} disabled={sending} aria-label="질문 창 닫기"><X size={20}/></button>{sent?<div className="success"><div className="success-icon"><Check size={30}/></div><h2 id="question-heading">질문을 전달했어요</h2><p>교수자가 확인한 후 <strong>{identity.email}</strong>로 답변합니다.</p><p className="muted">접수 번호 {sent.slice(0,8)} · 답변 시점은 교수자 확인 일정에 따라 달라집니다.</p><button className="primary" onClick={()=>setModal(false)}>학습으로 돌아가기</button></div>:<><span className="mini-label">ASK YOUR PROFESSOR</span><h2 id="question-heading">교수자에게 질문 남기기</h2><p className="muted">{topic.title} · 답변은 이메일로 보내드립니다.</p><form onSubmit={submit}><div className="form-row"><label>이름<input autoFocus required maxLength={50} autoComplete="name" value={identity.name} onChange={e=>setIdentity({...identity,name:e.target.value})} placeholder="홍길동"/></label><label>학번<input required pattern="[A-Za-z0-9-]{3,30}" maxLength={30} value={identity.studentId} onChange={e=>setIdentity({...identity,studentId:e.target.value})} placeholder="20260001"/></label></div><label>답변 받을 이메일<input required type="email" maxLength={254} autoComplete="email" value={identity.email} onChange={e=>setIdentity({...identity,email:e.target.value})} placeholder="student@school.ac.kr"/></label><label>질문<textarea required minLength={5} maxLength={3000} rows={5} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="어떤 부분이 어려웠는지 구체적으로 적어주세요."/></label>{history.length>0&&<label className="checkbox"><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/>이 주제의 튜터 대화도 함께 전달하기 (선택)</label>}<label className="checkbox"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>질문 답변을 위한 이름·학번·이메일 수집에 동의합니다.</label><p className="fine-print">제출 내용은 담당 교수자만 확인합니다. 답변 목적에 한해 보관하며 삭제는 교수자에게 요청할 수 있습니다.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={sending} type="submit"><Send size={17}/>{sending?'전달 중…':'질문 제출하기'}</button></form></>}</section></div>}
 </div>;
}


